---
version: "3.7"
services:
  checkout-api:
    build:
      context: .
    image: checkout
    environment:
      AWS_REGION: REGIONNAME
      CHECKOUT_TABLE_NAME: CHECKOUTTABLENAME
  checkout-proxy:
    build:
      context: ./nginx
    image: checkoutproxy
    ports:
      - "80:80"
    environment:
      AWS_REGION: REGIONNAME
      CHECKOUT_TABLE_NAME: CHECKOUTTABLENAME